server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Базовые заголовки для статики SPA
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
}
